compressionLevel: mixed

enableColors: true

enableGlobalCache: true

enableMessageNames: false

enableProgressBars: true

nodeLinker: node-modules

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
